### ISSUE TITLE
Admin panel unexpectedly closes connection.

### ISSUE THREAD

**Issue by MoonBarc** [gimkit/blueboat#3]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
Hi! I just installed blueboat and made a little script that starts the server and makes a room. So I tried to go into the admin panel by going to localhost:4000/blueboat-panel. But it says that the connection was unexpectedly closed. So I tried running the example too, but the same thing happened.

* **Other information**
Unfortunately the last thing the console said was Listening on port 4000.

**Comment by joshfeinsilber** [comment]
Hey @MoonBarc , are you getting this error when you click into a room?

**Comment by MoonBarc** [comment]
@joshfeinsilber It's happening when I try to access the panel. Right when I go to localhost:4000 it closes on the spot.

**Comment by joshfeinsilber** [comment]
@MoonBarc Can you send over a link to your repo? I can checkout the code.

**Comment by MoonBarc** [comment]
Since I couldn't find my old repo, I tried making a new one... seems as if it works! I must've done something odd.
Thanks for your time :)
